name: GDSAI Local
values:
  - key: base_url
    value: 'http://localhost:8000'
    enabled: true
    type: default
  - key: test_email
    value: testuser@example.com
    enabled: true
    type: default
  - key: test_password
    value: 'TestPass123!'
    enabled: true
    type: default
  - key: access_token
    value: ''
    enabled: true
    type: default
  - key: refresh_token
    value: ''
    enabled: true
    type: default
