import os

content = (
    '$kind: http-request\n'
    'name: Login\n'
    'description: |-\n'
    '  Authenticates an existing user using email and password. Returns a JWT access token and refresh token.\n'
    '\n'
    '  **Request Body:**\n'
    '  | Field | Type | Required | Description |\n'
    '  |---|---|---|---|\n'
    '  | email | string | \u2705 | User\'s email address |\n'
    '  | password | string | \u2705 | Account password |\n'
    '\n'
    '  **Success Response (200 OK):**\n'
    '  ```json\n'
    '  {\n'
    '    "access": "<jwt_access_token>",\n'
    '    "refresh": "<jwt_refresh_token>"\n'
    '  }\n'
    '  ```\n'
    '\n'
    '  **Error Responses:**\n'
    '  - `401 Unauthorized` \u2014 Invalid credentials\n'
    '  - `400 Bad Request` \u2014 Missing fields\n'
    '\n'
    '  > \u2699\ufe0f On success, `access_token` and `refresh_token` are automatically saved to the active environment.\n'
    'method: POST\n'
    "url: '{{base_url}}/api/v1/auth/login/'\n"
    'order: 2000\n'
    'headers:\n'
    '  - key: Content-Type\n'
    '    value: application/json\n'
    'body:\n'
    '  type: json\n'
    '  content: |-\n'
    '    {\n'
    '      "email": "{{test_email}}",\n'
    '      "password": "{{test_password}}"\n'
    '    }\n'
    'scripts:\n'
    '  - type: afterResponse\n'
    '    language: text/javascript\n'
    '    code: |-\n'
    '      pm.test("Status code is 200", function () {\n'
    '          pm.response.to.have.status(200);\n'
    '      });\n'
    '\n'
    '      pm.test("Response has access and refresh fields", function () {\n'
    '          var jsonData = pm.response.json();\n'
    '          pm.expect(jsonData).to.have.property("access");\n'
    '          pm.expect(jsonData).to.have.property("refresh");\n'
    '      });\n'
    '\n'
    '      pm.test("Access token is a non-empty string", function () {\n'
    '          var jsonData = pm.response.json();\n'
    '          pm.expect(jsonData.access).to.be.a("string").and.to.have.length.above(0);\n'
    '      });\n'
    '\n'
    '      pm.test("Response time is less than 2000ms", function () {\n'
    '          pm.expect(pm.response.responseTime).to.be.below(2000);\n'
    '      });\n'
    '\n'
    '      var jsonData = pm.response.json();\n'
    '      if (jsonData.access) {\n'
    '          pm.environment.set("access_token", jsonData.access);\n'
    '          pm.environment.set("refresh_token", jsonData.refresh);\n'
    '      }\n'
)

filepath = r'postman/collections/GDSAI Auth API/Auth/Login.request.yaml'
os.makedirs(os.path.dirname(filepath), exist_ok=True)
with open(filepath, 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)
print('Done')
