# Generated by Django 6.0.6 on 2026-07-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "location",
                    models.CharField(
                        help_text="e.g. Auditorium A, or Online", max_length=255
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(blank=True, null=True, upload_to="events/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Senior Software Engineer",
                        max_length=255,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, help_text="e.g. Google", max_length=255
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="speakers/"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, verbose_name="Twitter / X URL"),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn URL")),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="Personal Website URL"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Specific room or venue section",
                        max_length=255,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="events.event",
                    ),
                ),
                (
                    "speakers",
                    models.ManyToManyField(
                        blank=True, related_name="sessions", to="events.speaker"
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
