# Generated by Django 6.0.6 on 2026-07-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_apikey_session_presentation_slides_attendee_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="kahoot_url",
            field=models.URLField(
                blank=True,
                help_text="Link to external Kahoot or Slido quiz",
                max_length=500,
                null=True,
            ),
        ),
    ]
