# Generated by Django 6.0.6 on 2026-07-28 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_session_kahoot_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="attendee",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendee",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendee",
            name="payment_status",
            field=models.CharField(
                choices=[("PAID", "Paid"), ("UNPAID", "Unpaid")],
                default="UNPAID",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="attendee",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendees",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="attendee",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendees",
                to="events.ticket",
            ),
        ),
    ]
