# Generated by Django 6.0.6 on 2026-07-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_ticket_attendee_is_registered_attendee_paid_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="receipt_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
